trigger:
- feature-ms-rodrigoCortes-mensaje

pool:
  vmImage: ubuntu-latest

steps:

- script: |
      git fetch --unshallow
  displayName: 'Convert to non-shallow Clone'

- task: Gradle@3
  inputs:
      gradleWrapperFile: 'gradlew'
      workingDirectory: '$(Build.SourcesDirectory)'
      tasks: 'build test jacocoTestReport'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false
  displayName: Build

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'usach-devops-2023'
    projectKey: 'Usach-DevOps-2023_microservicio-spring'
    projectName: 'microservicio-spring'
  displayName: 'SonarCloud Prepare'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    workingDirectory: '$(Build.SourcesDirectory)'
    tasks: 'sonarqube'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false
  displayName: Run SonarCloud

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/build/reports/jacoco/test/jacocoTestReport.xml'
    #pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java/'
    reportDirectory: '$(System.DefaultWorkingDirectory)/build/reports/jacoco/test'
    additionalCodeCoverageFiles: '$(System.DefaultWorkingDirectory)/**/*.exec'
    failIfCoverageEmpty: true
  displayName: 'Publish Code Coverage Results'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    command: 'login'
  displayName: 'Docker Login'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'rcortesz/microservicio-laboratory'
    command: 'build'
    Dockerfile: '**/Dockerfile'
  displayName: 'Docker Build'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'rcortesz/microservicio-laboratory'
    command: 'push'
  displayName: 'Docker Push'