trigger:
- feature-ms-rodrigoCortes-mensaje

pool:
  vmImage: ubuntu-latest

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'usach-devops-2023'
    projectKey: 'Usach-DevOps-2023_microservicio-spring'
    projectName: 'microservicio-spring'
  displayName: 'SonarCloud Prepare'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build jacocoTestReport' #jacocoTestCoverageVerification
    publishJUnitResults: true
    testResultsFiles: '**/*Test*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false
  displayName: Build

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: 'build/reports/jacoco/test/jacocoTestReport.xml'
    reportDirectory: 'build/reports/jacoco/test'
    failIfCoverageEmpty: true
  displayName: 'Publish code coverage results'

- script: |
    wget -O apache-jmeter-5.4.3.tgz https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.4.3.tgz
    tar -xzf apache-jmeter-5.4.3.tgz
    rm apache-jmeter-5.4.3.tgz
  displayName: 'Download JMeter'

- script: |
    ./apache-jmeter-5.4.3/bin/jmeter.sh -n -t src/test/jmx/PerformanceTesting.jmx -l src/test/jmx/results.jtl
  displayName: 'Run JMeter Tests'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/results.jtl'

- script: |
    echo "Folder: $(System.DefaultWorkingDirectory)"
    # Parse the JTL file and calculate the error percentage
    totalRequests=$(grep -c "<httpSample" src/test/jmx/results.jtl)
    errorRequests=$(grep -c "<httpSample.*s=\"false\"" src/test/jmx/results.jtl)
    errorPercentage=$(awk "BEGIN {printf \"%.2f\", (${errorRequests}/${totalRequests})*100}")

    # Print the error percentage
    echo "Error Percentage: ${errorPercentage}%"
    
    # Fail the pipeline if the error percentage exceeds a threshold
    if (( $(awk "BEGIN {print (${errorPercentage} > 10 ? 1 : 0)}") )); then
      echo "Error percentage exceeds threshold. Failing the pipeline."
      exit 1
    fi
  displayName: 'Calculate Error Percentage'