trigger:
- feature-ms-rodrigoCortes-mensaje

pool:
  vmImage: ubuntu-latest

steps:

- task: Gradle@2
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    tasks: 'clean build'
    gradleWrapperFile: 'gradlew'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    codeCoverageToolOption: 'jacoco'
    codeCoverageClassFilesDirectories: 'build/classes/java/main'
    #codeCoverageSourceDirectories: 'src/main/java'
    #codeCoverageReportFiles: '**/jacoco.xml'
    sonarQubeRunAnalysis: false
  displayName: 'Build with Gradle and run tests'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/build/reports/jacoco/test/jacocoTestReport.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/build/reports/jacoco/test'
    failIfCoverageEmpty: true
  displayName: 'Publish code coverage results'