trigger:
- feature-ms-rodrigoCortes-mensaje

pool:
  vmImage: ubuntu-latest

steps:

- task: Gradle@3
  inputs:
    #workingDirectory: '$(System.DefaultWorkingDirectory)'
    gradleWrapperFile: 'gradlew'
    #codeCoverageToolOption: 'JaCoCo'
    tasks: 'build jacocoTestReport' #jacocoTestCoverageVerification
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
  displayName: Build/TestCoverage

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: 'build/reports/jacoco/test/jacocoTestReport.xml'
    reportDirectory: 'build/reports/jacoco/test'
    failIfCoverageEmpty: true
  displayName: 'Publish code coverage results'