trigger:
- feature-ms-rodrigoCortes-mensaje

pool:
  vmImage: ubuntu-latest

steps:

- task: Gradle@3
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    gradleWrapperFile: 'gradlew'
    tasks: 'build jacocoTestReport jacocoTestCoverageVerification'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
  displayName: Build/TestCoverage

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      minimum_coverage=$(grep "minimum=" build.gradle | grep -o "[0-9]*\.[0-9]*")
      coverage=$(grep "LINE" build/reports/jacoco/test/html/index.html | head -n1 | grep -o "[0-9]*\.[0-9]*")
      if (( $(echo "$coverage < $minimum_coverage" |bc -l) )); then
        echo "Code coverage ($coverage) is less than the required minimum ($minimum_coverage)"
        exit 1
      fi

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    command: 'login'
  displayName: 'Docker Login'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'rcortesz/microservicio-laboratory'
    command: 'build'
    Dockerfile: '**/Dockerfile'
  displayName: 'Docker Build'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'rcortesz/microservicio-laboratory'
    command: 'push'
  displayName: 'Docker Push'