apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicespring-deployment
  labels:
    app: microservicespring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicespring
  template:
    metadata:
      labels:
        app: microservicespring
    spec:
      containers:
      - name: microservicespring
        image: rcortesz/microservicio-laboratory:163
        ports:
        - containerPort: 8080